Repository nextcloud/files_antivirus, pull requests merged in 2018-07, with the labels that each got.

#87 Only scan the full file
  lib/AppInfo/Application.php
  lib/AvirWrapper.php
  tests/AvirWrapperTest.php
Labels: 3. to review, enhancement

#91 Use GitHub emojis 😔
  README.md
Labels: 3. to review

#90 Wrong screenshot-branch
  README.md
Labels: 3. to review, bug
