Repository nextcloud/files_antivirus, pull requests merged in 2023-05, with the labels that each got.

#272 [master] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies

#277 feat: add support for Nextcloud 27
  appinfo/info.xml
Labels: enhancement, 3. to review

#279 v5.1.0
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review
