Repository nextcloud/files_antivirus, pull requests merged in 2024-03, with the labels that each got.

#319 Updating phpunit-mysql.yml workflow from template
  .github/workflows/phpunit-mysql.yml
Labels: dependencies

#320 feat: detect timeouts for clam daemon
  lib/Scanner/ExternalClam.php
Labels: 3. to review

#304 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm-matrix.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated, feedback-requested
