Repository nextcloud/files_antivirus, pull requests merged in 2024-06, with the labels that each got.

#342 Make the error message `The ClamAV module is not in daemon mode.` mor…
  lib/Scanner/ExternalClam.php
Labels: enhancement, 3. to review

#346 fix: return a fresh scanner instance
  lib/AppInfo/Application.php
  tests/Scanner/ScannerFactoryTest.php
Labels: bug, 3. to review

#340 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#349 fix: handle icap responses with no encapsulated headers
  lib/ICAP/ResponseParser.php
  tests/ICAP/ResponseParserTest.php
  tests/data/icap/null-body.txt
Labels: 3. to review
