Repository nextcloud/files_antivirus, pull requests merged in 2025-04, with the labels that each got.

#433 chore: add codeowners file
  .github/CODEOWNERS
Labels: 3. to review

#436 fix: clean up obsolete etag column
  lib/Migration/Version60100Date20250424072838.php
Labels: bug, 3. to review, backport-request

#429 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#439 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#440 fix: exclude groupfolder trash and version files
  lib/BackgroundJob/BackgroundScanner.php
Labels: bug, 3. to review
