Repository nextcloud/files_antivirus, pull requests merged in 2025-02, with the labels that each got.

#421 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#420 chore(deps): bump nextcloud/ocp to dev-master (and peers)
  composer.json
  composer.lock
Labels: 3. to review, technical debt

#427 fix: handle null mount points gracefully
  lib/AvirWrapper.php
  lib/Scanner/ScannerFactory.php
  tests/AvirWrapperTest.php
Labels: bug, 3. to review, backport-request
