Repository nextcloud/files_antivirus, pull requests merged in 2025-09, with the labels that each got.

#495 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#482 fix: extract actual path when scanning ocTransferId files
  lib/AppInfo/Application.php
  lib/AvirWrapper.php
  lib/Scanner/ICAP.php
  tests/AvirWrapperTest.php
Labels: bug, 3. to review, backport-request

#505 chore(release): v6.0.5
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#506 chore(release): v5.6.6
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review
